executable            = /afs/cern.ch/work/d/dannc/public/MuonBackground/muons_up/muon_background.sh
arguments             = $(ClusterID) $(ProcId)
output                = output/passingmu.$(ClusterId).$(ProcId).out
error                 = error/passingmu.$(ClusterId).$(ProcId).err
log                   = log/passingmu.$(ClusterId).log
getenv = False
notification = Never
RequestCpus = 5
should_transfer_files = YES
+JobFlavour             ="testmatch"
queue 26

