executable            = /afs/cern.ch/work/d/dannc/public/MuonBackground/muonDis_sim/digiMuDis-Analysis.sh
arguments             = $(ProcId) $(ClusterId) 
output                = /afs/cern.ch/work/d/dannc/public/MuonBackground/muonDis_sim/output/digiMuDis-Analysis.$(ClusterId).$(ProcId).out
error                 = /afs/cern.ch/work/d/dannc/public/MuonBackground/muonDis_sim/error/digiMuDis-Analysis.$(ClusterId).$(ProcId).err
log                   = /afs/cern.ch/work/d/dannc/public/MuonBackground/muonDis_sim/log/digiMuDis-Analysis.$(ClusterId).log
getenv = false
notification = Error
notify_user = daniele.centanni@cern.ch
should_transfer_files = YES
+AccountingGroup = "group_u_SNDLHC.users"
+JobFlavour             ="longlunch"
on_exit_remove = (ExitBySignal == False) && (ExitCode == 0)
max_retries = 3
queue 20
